In [1]:
"""
Cuando trabajamos con Scikit las Features ya sean categoricas o numericas deben se un vertor.
Esta libreria y Machine L. en general trabaja mejor cuando las variables categoricas son numerico y a la vez estos estan
Encodados. (en formato de 0 y 1) para evitar que un valor se apodera de la prediccion.
Estos pasos son iguales tanto para una Regresion como para clasificacion.

1) Cargams el dataset limpio (mission values, feature ING, duplicats, etc).
2) Creamos un encoder para una sola variable categorica y lo apendeamos a un vector llamado Features.
3) creamos una funcion que recibe como parametro toda la columna categoria y deveuleve el Enconder que sera apendeado 
   al vector Feature.
4) Es importante si hay un error correr todo desde el punto 3 porque sino iremos appendeando valores al vector y seria incorrecto.
5) agregamos las variable nuvericas al mismo vector Features.
6) si hay un error volver a correr todo desde el punto 3.
7) Hacemos un Split de los datos usando las funciones Scikit
8) Hacemos un rescaling de los datos nuemricos, debemos recordar o saber donde empezaban los mismo para indicarlo 
    en el slicer y dicer. *
    
por ejemplo: en este caso de prueba los datos categoricos terminan en la columna 14 entonces en el slicer para hacer el rescaling 
ponemos que empiece en 14 y automaticamente tomara la coluna 15.
x_train[:,14:] -> empieza a partir de la 15
"""

'\nCuando trabajamos con Scikit las Features ya sean categoricas o numericas deben se un vertor.\nEsta libreria y Machine L. en general trabaja mejor cuando las variables categoricas son numerico y a la vez estos estan\nEncodados. (en formato de 0 y 1) para evitar que un valor se apodera de la prediccion.\n'

In [49]:
import pandas as pd
from sklearn import preprocessing
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
import math

%matplotlib inline

In [50]:
## Una vez termiando con la limpieza de datos guardamos un archivo con la info limpia para comerzar con el proceso de ML.

In [51]:
data = pd.read_csv('Auto_Data_Preped.csv')
data.head(5)

symboling         make fuel_type aspiration num_of_doors       body_style  \
0          3  alfa-romero       gas        std          two  hardtop_convert   
1          3  alfa-romero       gas        std          two  hardtop_convert   
2          1  alfa-romero       gas        std          two        hatchback   
3          2         audi       gas        std         four            sedan   
4          2         audi       gas        std         four            sedan   

  drive_wheels engine_location  wheel_base  length    ...      fuel_system  \
0          rwd           front        88.6   168.8    ...             mpfi   
1          rwd           front        88.6   168.8    ...             mpfi   
2          rwd           front        94.5   171.2    ...             mpfi   
3          fwd           front        99.8   176.6    ...             mpfi   
4          4wd           front        99.4   176.6    ...             mpfi   

   bore  stroke compression_ratio horsepower  peak_rpm city_mpg  highway_mpg  \
0  3.47    2.68               9.0        111      5000       21           27   
1  3.47    2.68               9.0        111      5000       21           27   
2  2.68    3.47               9.0        154      5000       19           26   
3  3.19    3.40              10.0        102      5500       24           30   
4  3.19    3.40               8.0        115      5500       18           22   

   price  log_price  
0  13495   9.510075  
1  16500   9.711116  
2  16500   9.711116  
3  13950   9.543235  
4  17450   9.767095  

[5 rows x 26 columns]

In [52]:
## primero creamos el Vector Feauture para una sola variable y luego le appendeamos las otras que faltan.
print(data['body_style'].unique())
Features = data['body_style']
enc = preprocessing.LabelEncoder()
enc.fit(Features)
Features = enc.transform(Features)
print(Features)


['hardtop_convert' 'hatchback' 'sedan' 'wagon']
[0 0 1 2 2 2 2 3 2 2 2 2 2 2 2 2 2 1 1 2 1 1 1 1 2 2 2 3 1 1 1 1 1 1 2 3 1
 1 2 2 2 2 2 1 2 2 2 1 1 1 2 2 1 2 1 2 2 1 2 2 2 3 0 2 2 0 2 0 1 1 1 1 1 1
 1 1 1 1 2 2 2 2 2 2 2 2 3 2 1 2 3 0 1 2 2 3 2 1 1 1 2 2 3 3 2 2 3 3 2 2 2
 1 1 1 2 2 3 1 1 0 0 0 1 2 1 2 1 2 1 1 1 2 2 2 2 2 3 3 3 3 1 1 1 3 3 3 2 1
 2 1 2 1 2 2 1 2 1 0 0 1 0 1 0 2 2 1 2 1 1 1 2 3 2 2 2 2 2 2 2 0 1 2 2 3 2
 3 2 3 2 3 2 2 2 2 2]


In [53]:
## Ahora creamos el vector encoder para el vector creado anteriormante.
ohe = preprocessing.OneHotEncoder()
encoded = ohe.fit(Features.reshape(-1,1))
Features = encoded.transform(Features.reshape(-1,1)).toarray()
Features[:10,:]



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [54]:
def encode_variables(cat_variables):
    Features = cat_variables
    enc = preprocessing.LabelEncoder()
    enc.fit(Features)
    Features = enc.transform(Features)
    ohe = preprocessing.OneHotEncoder()
    encoded = ohe.fit(Features.reshape(-1,1))
    return  encoded.transform(Features.reshape(-1,1)).toarray()

variables = ['fuel_type', 'aspiration', 'drive_wheels', 'num_of_cylinders']

for col in variables:
    temp = encode_variables(data[col])
    Features = np.concatenate([Features,temp], axis = 1)
    
print(Features.shape)
print(Features[:2,:])

    
    

(195, 14)
[[1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you us

In [55]:
## ahor que ya tenemos las variables categorias en un solo NP array 
## le agregamos las variables numericas que aun no han sido estandarizadas o escaladaas (Scaling)

Features = np.concatenate([Features, np.array(data[['curb_weight', 'horsepower', 'city_mpg']])], axis = 1)
print(Features[:2,:])
print(Features.shape)

[[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 1.000e+00
  0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00 1.000e+00
  2.548e+03 1.110e+02 2.100e+01]
 [1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.000e+00 1.000e+00
  0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00 1.000e+00
  2.548e+03 1.110e+02 2.100e+01]]
(195, 17)


In [56]:
## Con las variables numericas en su lugar hacemos un Split de datos

nr.seed(9988)
labels = np.array(data['log_price'])
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 40)
x_train = Features[indx[0],:]
y_train = np.ravel(labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(labels[indx[1]])

In [57]:
## y funalmente un rescale de la variable numerica.

scaler = preprocessing.StandardScaler().fit(x_train[:,14:])
x_train[:,14:] = scaler.transform(x_train[:,14:])
x_test[:,14:] = scaler.transform(x_test[:,14:])
print(x_train.shape)
x_train[:5,:]

(155, 17)


array([[ 0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        , -0.5384069 ,
        -1.26225437,  1.33602998],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  1.        ,  0.96837381,
         1.51064566, -1.00126852],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        , -0.86156658,
        -0.88897936,  0.71275038],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  1.        , -0.27559631,
        -0.51570436

In [ ]:
## con esto ya podemos empezar a aplicar nuestro modelo de regresion o clasificaion.